//==========================================================================
//==               Copyright (c) 2025 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 02/21/2025 10:50:21
//== Synopsys Memory Release: V04R31SZ_31JAN2021
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/idtk
//== IDDK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================


//==========================================================================
//==               Copyright (c) 2025 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 02/21/2025 10:50:21
//== Synopsys Memory Release: V04R31SZ_31JAN2021
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/idtk
//== IDDK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================


`timescale 1ns / 1ps
module MBH_MSBL_IN22FDX_S1P_BFRG_W00320B032M08C128
   (
    input CLK,
    input CEN,
    input RDWEN,
    input DEEPSLEEP,
    input POWERGATE,
    input  [1+5+3-1:0] a,
    input [32-1:0] D,
    input [32-1:0] BW,
    input T_BIST,
    input T_LOGIC,
    input T_CEN,
    input T_RDWEN,
    input T_DEEPSLEEP,
    input T_POWERGATE,
    input T_STAB,
    input T_WBT,
    input  [1+5+3-1:0] t_a,
    input [32-1:0] T_D,
    input [32-1:0] T_BW,
    input MA_SAWL0,
    input MA_SAWL1,
    input MA_WL0,
    input MA_WL1,
    input MA_WRAS0,
    input MA_WRAS1,
    input MA_WRASD,
    input  RBE,
    input [7-1:0] RBF0A,
    output QRB,
    output [32-1:0] Q,
    output OBSV_CTL
    );

// VSIA_Soft_IP_Tag % Vendor SYNOPSYS % Product 22FDX % Version v00r50 % Metric 100 % IP_Owner VTMDC % Celltype IP % Cell_Id MBH_MSBL_IN22FDX_S1P_BFRG_W00320B032M08C128 % Signature 100 % Tag_Spec 3.0 % Date_Time 20250221 % Process_Step Source

   wire [1-1:0]   n_as;
   wire [1-1:0]   n_t_as;
   wire [5-1:0]   n_aw;
   wire [3-1:0]   n_ac;
   wire [5-1:0]   n_t_aw;
   wire [3-1:0]   n_t_ac;
   assign {n_aw[5-1:2], n_as, n_aw[1:0], n_ac} = a;
   assign {n_t_aw[5-1:2], n_t_as, n_t_aw[1:0], n_t_ac} = t_a;
   wire [1:0] n_ma_sawl = { MA_SAWL1, MA_SAWL0 };
   wire [1:0] n_ma_wl   = { MA_WL1,   MA_WL0   };
   wire [1:0] n_ma_wras = { MA_WRAS1, MA_WRAS0 };
   IN22FDX_S1P_BFRG_W00320B032M08C128 S1P
     (
      .CLK         (CLK),
      .CEN         (CEN),
      .RDWEN       (RDWEN),
      .DEEPSLEEP   (DEEPSLEEP),
      .POWERGATE   (POWERGATE),
      .AS          (n_as),
      .AW          (n_aw),
      .AC          (n_ac),
      .D           (D),
      .BW          (BW),
      .T_BIST      (T_BIST),
      .T_LOGIC     (T_LOGIC),
      .T_CEN       (T_CEN),
      .T_RDWEN     (T_RDWEN),
      .T_DEEPSLEEP (T_DEEPSLEEP),
      .T_POWERGATE (T_POWERGATE),
      .T_STAB      (T_STAB),
      .T_WBT       (T_WBT),
      .T_AS        (n_t_as),
      .T_AW        (n_t_aw),
      .T_AC        (n_t_ac),
      .T_D         (T_D),
      .T_BW        (T_BW),
      .MA_SAWL     (n_ma_sawl),
      .MA_WL       (n_ma_wl),
      .MA_WRAS     (n_ma_wras),
      .MA_WRASD    (MA_WRASD),
      .RBE         (RBE),
      .RBF0A       (RBF0A),
      .QRB         (QRB),
      .Q           (Q),
      .OBSV_CTL    (OBSV_CTL)
      );
endmodule
