//==========================================================================
//==               Copyright (c) 2025 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 02/21/2025 10:50:21
//== Synopsys Memory Release: V04R31SZ_31JAN2021
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/idtk
//== IDDK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================


//==========================================================================
//==               Copyright (c) 2025 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 02/21/2025 10:50:21
//== Synopsys Memory Release: V04R31SZ_31JAN2021
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/idtk
//== IDDK_ROOT: /users/xcarril/scripts_22nm/in_gf22fdx_s1pRELV04R31SZ-Merge/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================


`timescale 1ns / 1ps
module MBH_ZSBL_IN22FDX_S1P_BFRG_W00320B032M08C128
   (
    input  clk,
    input  cen,
    input  rdwen,
    input  deepsleep,
    input  powergate,
    input  [1+5+3-1:0] a,
    input  [32-1:0] d,
    input  [32-1:0] bw,
    output [32-1:0] q
    );

// VSIA_Soft_IP_Tag % Vendor SYNOPSYS % Product 22FDX % Version v00r50 % Metric 100 % IP_Owner VTMDC % Celltype IP % Cell_Id MBH_ZSBL_IN22FDX_S1P_BFRG_W00320B032M08C128 % Signature 100 % Tag_Spec 3.0 % Date_Time 20250221 % Process_Step Source

   wire    n_qrb;
   wire [32-1:0]    n_t_d = {32{1'b0}};
   wire [32-1:0]    n_t_bw = {32{1'b0}};
   wire    n_rbe = {1{1'b0}};
   wire [7-1:0] n_rbf0a = {7{1'b0}};
   wire [7-1:0] n_rbf1a = {7{1'b0}};
   wire [1+5+3-1:0] n_t_a = {1+5+3{1'b0}};
   wire                    n_obsv_ctl;
   MBH_MSBL_IN22FDX_S1P_BFRG_W00320B032M08C128 MBH0
     (
      .CLK         (clk),
      .CEN         (cen),
      .RDWEN       (rdwen),
      .DEEPSLEEP   (deepsleep),
      .POWERGATE   (powergate),
      .a           (a),
      .D           (d),
      .BW          (bw),
      .T_BIST      (1'b0),
      .T_LOGIC     (1'b0),
      .T_CEN       (1'b0),
      .T_RDWEN     (1'b0),
      .T_DEEPSLEEP (1'b0),
      .T_POWERGATE (1'b0),
      .T_STAB      (1'b0),
      .T_WBT       (1'b0),
      .t_a         (n_t_a),
      .T_D         (n_t_d),
      .T_BW        (n_t_bw),
      .MA_SAWL0    (1'b0),
      .MA_SAWL1    (1'b0),
      .MA_WL0      (1'b0),
      .MA_WL1      (1'b0),
      .MA_WRAS0    (1'b0),
      .MA_WRAS1    (1'b0),
      .MA_WRASD    (1'b0),
      .Q           (q),
      .QRB         (n_qrb),
      .RBE         (n_rbe),
      .RBF0A       (n_rbf0a),
      .OBSV_CTL    (n_obsv_ctl)
      );
endmodule
